# Generated by Django 6.0.2 on 2026-02-09 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimereport',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='crimereport',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='user',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='crime_type_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='crime_type',
            field=models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('burglary', 'Burglary'), ('vandalism', 'Vandalism'), ('fraud', 'Fraud'), ('other', 'Other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='CrimeHotspot',
        ),
    ]
